#!/bin/bash
cp -R JayScrum/Images/ JayScrum_Apple/JayScrum/www/Images
cp -R JayScrum/Properties/ JayScrum_Apple/JayScrum/www/Properties
cp -R JayScrum/Scripts/ JayScrum_Apple/JayScrum/www/Scripts
cp -R JayScrum/Styles/ JayScrum_Apple/JayScrum/www/Styles
cp JayScrum/index.html JayScrum_Apple/JayScrum/www
cp JayScrum/Scripts/cordova-1.9.0ios.js JayScrum_Apple/JayScrum/www/Scripts/cordova-1.9.0.js
rm JayScrum_Apple/JayScrum/www/Scripts/cordova-1.9.0ios.js