//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Implementation
{
    
    #region WorkItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class WorkItem :
        global::LightSwitchApplication.WorkItem.DetailsClass.IImplementation
    {
        partial void OnWorkItem_ProjectChanged()
        {
            this.___OnPropertyChanged("WorkItem_Project");
            this.___OnPropertyChanged("Project");
        }
        
        partial void OnWorkItem_SprintChanged()
        {
            this.___OnPropertyChanged("WorkItem_Sprint");
            this.___OnPropertyChanged("Sprint");
        }
        
        partial void OnWorkItem_WorkItemChanged()
        {
            this.___OnPropertyChanged("WorkItem_WorkItem");
            this.___OnPropertyChanged("Parent");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnTitleChanged()
        {
            this.___OnPropertyChanged("Title");
        }
        
        partial void OnTypeChanged()
        {
            this.___OnPropertyChanged("Type");
        }
        
        partial void OnDescriptionChanged()
        {
            this.___OnPropertyChanged("Description");
        }
        
        partial void OnCreatedDateChanged()
        {
            this.___OnPropertyChanged("CreatedDate");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnChangedDateChanged()
        {
            this.___OnPropertyChanged("ChangedDate");
        }
        
        partial void OnChangedByChanged()
        {
            this.___OnPropertyChanged("ChangedBy");
        }
        
        partial void OnPriorityChanged()
        {
            this.___OnPropertyChanged("Priority");
        }
        
        partial void OnAssignedToChanged()
        {
            this.___OnPropertyChanged("AssignedTo");
        }
        
        partial void OnStateChanged()
        {
            this.___OnPropertyChanged("State");
        }
        
        partial void OnEffortChanged()
        {
            this.___OnPropertyChanged("Effort");
        }
        
        partial void OnBusinessValueChanged()
        {
            this.___OnPropertyChanged("BusinessValue");
        }
        
        partial void OnIsBlockedChanged()
        {
            this.___OnPropertyChanged("IsBlocked");
        }
        
        partial void OnRemainingWorkChanged()
        {
            this.___OnPropertyChanged("RemainingWork");
        }
        
        partial void OnReasonChanged()
        {
            this.___OnPropertyChanged("Reason");
        }
        
        partial void OnParentNameChanged()
        {
            this.___OnPropertyChanged("ParentName");
        }
        
        partial void OnProjectNameChanged()
        {
            this.___OnPropertyChanged("ProjectName");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.WorkItem.DetailsClass.IImplementation.Project
        {
            get
            {
                return this.Project;
            }
            set
            {
                this.Project = (global::LightSwitchApplication.Implementation.Project)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Project> __Project
        {
            get
            {
                if (this.___Project == null)
                {
                    this.___Project = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Project>(
                        this,
                        "Project",
                        new string[] { "WorkItem_Project" },
                        e => global::System.Object.Equals(e.Id, this.WorkItem_Project),
                        () => this._Project,
                        e => this._Project = e);
                }
                return this.___Project;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Project> ___Project;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.WorkItem.DetailsClass.IImplementation.Sprint
        {
            get
            {
                return this.Sprint;
            }
            set
            {
                this.Sprint = (global::LightSwitchApplication.Implementation.Sprint)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Sprint> __Sprint
        {
            get
            {
                if (this.___Sprint == null)
                {
                    this.___Sprint = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Sprint>(
                        this,
                        "Sprint",
                        new string[] { "WorkItem_Sprint" },
                        e => global::System.Object.Equals(e.Id, this.WorkItem_Sprint),
                        () => this._Sprint,
                        e => this._Sprint = e);
                }
                return this.___Sprint;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Sprint> ___Sprint;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.WorkItem.DetailsClass.IImplementation.Parent
        {
            get
            {
                return this.Parent;
            }
            set
            {
                this.Parent = (global::LightSwitchApplication.Implementation.WorkItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.WorkItem> __Parent
        {
            get
            {
                if (this.___Parent == null)
                {
                    this.___Parent = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.WorkItem>(
                        this,
                        "Parent",
                        new string[] { "WorkItem_WorkItem" },
                        e => global::System.Object.Equals(e.Id, this.WorkItem_WorkItem),
                        () => this._Parent,
                        e => this._Parent = e);
                }
                return this.___Parent;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.WorkItem> ___Parent;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.WorkItem.DetailsClass.IImplementation.Children
        {
            get
            {
                return this.Children;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.WorkItem> __Children
        {
            get
            {
                if (this.___Children == null)
                {
                    this.___Children = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.WorkItem>(
                        this,
                        "Children",
                        () => this._Children,
                        e => global::System.Object.Equals(e.WorkItem_WorkItem, this.Id));
                }
                return this.___Children;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.WorkItem> ___Children;
        
    }
    #endregion
    
    #region Project
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Project :
        global::LightSwitchApplication.Project.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        partial void OnDescriptionChanged()
        {
            this.___OnPropertyChanged("Description");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Project.DetailsClass.IImplementation.WorkItems
        {
            get
            {
                return this.WorkItems;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.WorkItem> __WorkItems
        {
            get
            {
                if (this.___WorkItems == null)
                {
                    this.___WorkItems = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.WorkItem>(
                        this,
                        "WorkItems",
                        () => this._WorkItems,
                        e => global::System.Object.Equals(e.WorkItem_Project, this.Id));
                }
                return this.___WorkItems;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.WorkItem> ___WorkItems;
        
    }
    #endregion
    
    #region Sprint
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Sprint :
        global::LightSwitchApplication.Sprint.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        partial void OnStartDateChanged()
        {
            this.___OnPropertyChanged("StartDate");
        }
        
        partial void OnFinishDateChanged()
        {
            this.___OnPropertyChanged("FinishDate");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Sprint.DetailsClass.IImplementation.WorkItems
        {
            get
            {
                return this.WorkItems;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.WorkItem> __WorkItems
        {
            get
            {
                if (this.___WorkItems == null)
                {
                    this.___WorkItems = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.WorkItem>(
                        this,
                        "WorkItems",
                        () => this._WorkItems,
                        e => global::System.Object.Equals(e.WorkItem_Sprint, this.Id));
                }
                return this.___WorkItems;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.WorkItem> ___WorkItems;
        
    }
    #endregion
    
    #region ApplicationDataObjectContext
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ApplicationDataObjectContext
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.WorkItem))
            {
                return new global::LightSwitchApplication.Implementation.WorkItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Project))
            {
                return new global::LightSwitchApplication.Implementation.Project();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Sprint))
            {
                return new global::LightSwitchApplication.Implementation.Sprint();
            }
            return null;
        }
    }
    #endregion
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class DataServiceFactory :
        global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.ApplicationData();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationDataObjectContext(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../ApplicationData.svc"));
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.WorkItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.WorkItem);
            }
            if (typeof(global::LightSwitchApplication.Project) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Project);
            }
            if (typeof(global::LightSwitchApplication.Sprint) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Sprint);
            }
            return null;
        }
    }
}
