//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class SprintsListDetail
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.SprintsListDetail, global::LightSwitchApplication.SprintsListDetail.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private SprintsListDetail() : base("LightSwitchApplication:SprintsListDetail")
        {
            global::LightSwitchApplication.SprintsListDetail.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static SprintsListDetail CreateInstance()
        {
            return new global::LightSwitchApplication.SprintsListDetail(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SprintsListDetail_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SprintsListDetail_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SprintsListDetail_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SprintsListDetail_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SprintsListDetail_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SprintsListDetail_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SprintsListDetail_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void Sprints_SelectionChanged();

        partial void Sprints_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Sprints_Loaded(bool succeeded);

        partial void WorkItems_SelectionChanged();

        partial void WorkItems_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WorkItems_Loaded(bool succeeded);

        /// <summary>
        /// Gets the Sprints visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Sprint> Sprints
        {
            get
            {
                return global::LightSwitchApplication.SprintsListDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.SprintsListDetail.DetailsClass.PropertySetProperties.Sprints);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Sprints_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Gets the WorkItems visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.WorkItem> WorkItems
        {
            get
            {
                return global::LightSwitchApplication.SprintsListDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.SprintsListDetail.DetailsClass.PropertySetProperties.WorkItems);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WorkItems_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.SprintsListDetail, global::LightSwitchApplication.SprintsListDetail.DetailsClass, global::LightSwitchApplication.SprintsListDetail.DetailsClass.PropertySet, global::LightSwitchApplication.SprintsListDetail.DetailsClass.CommandSet, global::LightSwitchApplication.SprintsListDetail.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.SprintsListDetail.DetailsClass.PropertySetProperties.Sprints;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.SprintsListDetail, global::LightSwitchApplication.SprintsListDetail.DetailsClass>.Entry
                __SprintsListDetailEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.SprintsListDetail, global::LightSwitchApplication.SprintsListDetail.DetailsClass>.Entry(
                    global::LightSwitchApplication.SprintsListDetail.DetailsClass.__SprintsListDetail_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.SprintsListDetail.DetailsClass.__SprintsListDetail_InvokeSavingEvent,
                    global::LightSwitchApplication.SprintsListDetail.DetailsClass.__SprintsListDetail_InvokeSavedEvent,
                    global::LightSwitchApplication.SprintsListDetail.DetailsClass.__SprintsListDetail_InvokeClosingEvent,
                    global::LightSwitchApplication.SprintsListDetail.DetailsClass.__SprintsListDetail_InvokeCreated,
                    global::LightSwitchApplication.SprintsListDetail.DetailsClass.__SprintsListDetail_InvokeActivated,
                    global::LightSwitchApplication.SprintsListDetail.DetailsClass.__SprintsListDetail_InvokeSaveErrorEvent);
            private static void __SprintsListDetail_InvokeInitializeDataWorkspace(global::LightSwitchApplication.SprintsListDetail s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.SprintsListDetail_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __SprintsListDetail_InvokeSavingEvent(global::LightSwitchApplication.SprintsListDetail s)
            {
                bool handled = false;
                s.SprintsListDetail_Saving(ref handled);
                return handled;
            }
            private static void __SprintsListDetail_InvokeSavedEvent(global::LightSwitchApplication.SprintsListDetail s)
            {
                s.SprintsListDetail_Saved();
            }
            private static bool __SprintsListDetail_InvokeClosingEvent(global::LightSwitchApplication.SprintsListDetail s)
            {
                bool cancel = false;
                s.SprintsListDetail_Closing(ref cancel);
                return cancel;
            }
            private static void __SprintsListDetail_InvokeCreated(global::LightSwitchApplication.SprintsListDetail s)
            {
                s.SprintsListDetail_Created();
            }
            private static void __SprintsListDetail_InvokeActivated(global::LightSwitchApplication.SprintsListDetail s)
            {
                s.SprintsListDetail_Activated();
            }
            private static bool __SprintsListDetail_InvokeSaveErrorEvent(global::LightSwitchApplication.SprintsListDetail s, global::System.Exception ex)
            {
                bool handled = false;
                s.SprintsListDetail_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.SprintsListDetail.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.SprintsListDetail.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.SprintsListDetail.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable SprintsQuery()
            {
                return this.Screen.DataWorkspace.ApplicationData.Sprints;
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable WorkItemsQuery()
            {
                if (this.Screen.Sprints.SelectedItem == null)
                {
                    return null;
                }

                global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.WorkItem> loader =
                    (global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.WorkItem>)((global::Microsoft.LightSwitch.Details.ILoadableProperty)this.Screen.Sprints.SelectedItem.Details.Properties.WorkItems).Loader;
                if (loader == null)
                {
                    return null;
                }

                return global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                    global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                        loader,
                        "Project"),
                    "Parent");
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SprintsListDetail, global::LightSwitchApplication.SprintsListDetail.DetailsClass, global::LightSwitchApplication.Sprint>.Data _Sprints;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SprintsListDetail, global::LightSwitchApplication.SprintsListDetail.DetailsClass, global::LightSwitchApplication.WorkItem>.Data _WorkItems;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.SprintsListDetail, global::LightSwitchApplication.SprintsListDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SprintsListDetail, global::LightSwitchApplication.SprintsListDetail.DetailsClass, global::LightSwitchApplication.Sprint> Sprints
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SprintsListDetail, global::LightSwitchApplication.SprintsListDetail.DetailsClass, global::LightSwitchApplication.Sprint>)base.GetItem(global::LightSwitchApplication.SprintsListDetail.DetailsClass.PropertySetProperties.Sprints);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SprintsListDetail, global::LightSwitchApplication.SprintsListDetail.DetailsClass, global::LightSwitchApplication.WorkItem> WorkItems
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SprintsListDetail, global::LightSwitchApplication.SprintsListDetail.DetailsClass, global::LightSwitchApplication.WorkItem>)base.GetItem(global::LightSwitchApplication.SprintsListDetail.DetailsClass.PropertySetProperties.WorkItems);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.SprintsListDetail, global::LightSwitchApplication.SprintsListDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.SprintsListDetail, global::LightSwitchApplication.SprintsListDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SprintsListDetail, global::LightSwitchApplication.SprintsListDetail.DetailsClass, global::LightSwitchApplication.Sprint>.Entry
                    Sprints = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SprintsListDetail, global::LightSwitchApplication.SprintsListDetail.DetailsClass, global::LightSwitchApplication.Sprint>.Entry(
                        "Sprints",
                        global::LightSwitchApplication.SprintsListDetail.DetailsClass.PropertySetProperties._Sprints_Stub,
                        global::LightSwitchApplication.SprintsListDetail.DetailsClass.PropertySetProperties._Sprints_Validate,
                        global::LightSwitchApplication.SprintsListDetail.DetailsClass.PropertySetProperties._Sprints_CreateQuery,
                        global::LightSwitchApplication.SprintsListDetail.DetailsClass.PropertySetProperties._Sprints_SelectionChanged,
                        global::LightSwitchApplication.SprintsListDetail.DetailsClass.PropertySetProperties._Sprints_OnCollectionChanged,
                        global::LightSwitchApplication.SprintsListDetail.DetailsClass.PropertySetProperties._Sprints_OnLoaded);
                private static void _Sprints_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SprintsListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SprintsListDetail, global::LightSwitchApplication.SprintsListDetail.DetailsClass, global::LightSwitchApplication.Sprint>.Data> c, global::LightSwitchApplication.SprintsListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._Sprints, sf);
                }
                private static void _Sprints_Validate(global::LightSwitchApplication.SprintsListDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Sprints_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Sprints_CreateQuery(global::LightSwitchApplication.SprintsListDetail.DetailsClass d, object[] args)
                {
                    return d.SprintsQuery();
                }
                private static void _Sprints_SelectionChanged(global::LightSwitchApplication.SprintsListDetail s)
                {
                    s.Sprints_SelectionChanged();
                }
                private static void _Sprints_OnCollectionChanged(global::LightSwitchApplication.SprintsListDetail s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Sprints_Changed(e);
                }
                private static void _Sprints_OnLoaded(global::LightSwitchApplication.SprintsListDetail s, bool succeeded)
                {
                    s.Sprints_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SprintsListDetail, global::LightSwitchApplication.SprintsListDetail.DetailsClass, global::LightSwitchApplication.WorkItem>.Entry
                    WorkItems = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SprintsListDetail, global::LightSwitchApplication.SprintsListDetail.DetailsClass, global::LightSwitchApplication.WorkItem>.Entry(
                        "WorkItems",
                        global::LightSwitchApplication.SprintsListDetail.DetailsClass.PropertySetProperties._WorkItems_Stub,
                        global::LightSwitchApplication.SprintsListDetail.DetailsClass.PropertySetProperties._WorkItems_Validate,
                        global::LightSwitchApplication.SprintsListDetail.DetailsClass.PropertySetProperties._WorkItems_CreateQuery,
                        global::LightSwitchApplication.SprintsListDetail.DetailsClass.PropertySetProperties._WorkItems_SelectionChanged,
                        global::LightSwitchApplication.SprintsListDetail.DetailsClass.PropertySetProperties._WorkItems_OnCollectionChanged,
                        global::LightSwitchApplication.SprintsListDetail.DetailsClass.PropertySetProperties._WorkItems_OnLoaded);
                private static void _WorkItems_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SprintsListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SprintsListDetail, global::LightSwitchApplication.SprintsListDetail.DetailsClass, global::LightSwitchApplication.WorkItem>.Data> c, global::LightSwitchApplication.SprintsListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._WorkItems, sf);
                }
                private static void _WorkItems_Validate(global::LightSwitchApplication.SprintsListDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.WorkItems_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _WorkItems_CreateQuery(global::LightSwitchApplication.SprintsListDetail.DetailsClass d, object[] args)
                {
                    return d.WorkItemsQuery();
                }
                private static void _WorkItems_SelectionChanged(global::LightSwitchApplication.SprintsListDetail s)
                {
                    s.WorkItems_SelectionChanged();
                }
                private static void _WorkItems_OnCollectionChanged(global::LightSwitchApplication.SprintsListDetail s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.WorkItems_Changed(e);
                }
                private static void _WorkItems_OnLoaded(global::LightSwitchApplication.SprintsListDetail s, bool succeeded)
                {
                    s.WorkItems_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class ProjectsListDetail
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.ProjectsListDetail, global::LightSwitchApplication.ProjectsListDetail.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private ProjectsListDetail() : base("LightSwitchApplication:ProjectsListDetail")
        {
            global::LightSwitchApplication.ProjectsListDetail.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static ProjectsListDetail CreateInstance()
        {
            return new global::LightSwitchApplication.ProjectsListDetail(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectsListDetail_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectsListDetail_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectsListDetail_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectsListDetail_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectsListDetail_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectsListDetail_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjectsListDetail_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void Projects_SelectionChanged();

        partial void Projects_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Projects_Loaded(bool succeeded);

        partial void WorkItems_SelectionChanged();

        partial void WorkItems_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WorkItems_Loaded(bool succeeded);

        /// <summary>
        /// Gets the Projects visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Project> Projects
        {
            get
            {
                return global::LightSwitchApplication.ProjectsListDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectsListDetail.DetailsClass.PropertySetProperties.Projects);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Projects_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Gets the WorkItems visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.WorkItem> WorkItems
        {
            get
            {
                return global::LightSwitchApplication.ProjectsListDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.ProjectsListDetail.DetailsClass.PropertySetProperties.WorkItems);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WorkItems_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.ProjectsListDetail, global::LightSwitchApplication.ProjectsListDetail.DetailsClass, global::LightSwitchApplication.ProjectsListDetail.DetailsClass.PropertySet, global::LightSwitchApplication.ProjectsListDetail.DetailsClass.CommandSet, global::LightSwitchApplication.ProjectsListDetail.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.ProjectsListDetail.DetailsClass.PropertySetProperties.Projects;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.ProjectsListDetail, global::LightSwitchApplication.ProjectsListDetail.DetailsClass>.Entry
                __ProjectsListDetailEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.ProjectsListDetail, global::LightSwitchApplication.ProjectsListDetail.DetailsClass>.Entry(
                    global::LightSwitchApplication.ProjectsListDetail.DetailsClass.__ProjectsListDetail_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.ProjectsListDetail.DetailsClass.__ProjectsListDetail_InvokeSavingEvent,
                    global::LightSwitchApplication.ProjectsListDetail.DetailsClass.__ProjectsListDetail_InvokeSavedEvent,
                    global::LightSwitchApplication.ProjectsListDetail.DetailsClass.__ProjectsListDetail_InvokeClosingEvent,
                    global::LightSwitchApplication.ProjectsListDetail.DetailsClass.__ProjectsListDetail_InvokeCreated,
                    global::LightSwitchApplication.ProjectsListDetail.DetailsClass.__ProjectsListDetail_InvokeActivated,
                    global::LightSwitchApplication.ProjectsListDetail.DetailsClass.__ProjectsListDetail_InvokeSaveErrorEvent);
            private static void __ProjectsListDetail_InvokeInitializeDataWorkspace(global::LightSwitchApplication.ProjectsListDetail s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.ProjectsListDetail_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __ProjectsListDetail_InvokeSavingEvent(global::LightSwitchApplication.ProjectsListDetail s)
            {
                bool handled = false;
                s.ProjectsListDetail_Saving(ref handled);
                return handled;
            }
            private static void __ProjectsListDetail_InvokeSavedEvent(global::LightSwitchApplication.ProjectsListDetail s)
            {
                s.ProjectsListDetail_Saved();
            }
            private static bool __ProjectsListDetail_InvokeClosingEvent(global::LightSwitchApplication.ProjectsListDetail s)
            {
                bool cancel = false;
                s.ProjectsListDetail_Closing(ref cancel);
                return cancel;
            }
            private static void __ProjectsListDetail_InvokeCreated(global::LightSwitchApplication.ProjectsListDetail s)
            {
                s.ProjectsListDetail_Created();
            }
            private static void __ProjectsListDetail_InvokeActivated(global::LightSwitchApplication.ProjectsListDetail s)
            {
                s.ProjectsListDetail_Activated();
            }
            private static bool __ProjectsListDetail_InvokeSaveErrorEvent(global::LightSwitchApplication.ProjectsListDetail s, global::System.Exception ex)
            {
                bool handled = false;
                s.ProjectsListDetail_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.ProjectsListDetail.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.ProjectsListDetail.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.ProjectsListDetail.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable ProjectsQuery()
            {
                return this.Screen.DataWorkspace.ApplicationData.Projects;
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable WorkItemsQuery()
            {
                if (this.Screen.Projects.SelectedItem == null)
                {
                    return null;
                }

                global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.WorkItem> loader =
                    (global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.WorkItem>)((global::Microsoft.LightSwitch.Details.ILoadableProperty)this.Screen.Projects.SelectedItem.Details.Properties.WorkItems).Loader;
                if (loader == null)
                {
                    return null;
                }

                return global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                    global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                        loader,
                        "Sprint"),
                    "Parent");
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.ProjectsListDetail, global::LightSwitchApplication.ProjectsListDetail.DetailsClass, global::LightSwitchApplication.Project>.Data _Projects;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.ProjectsListDetail, global::LightSwitchApplication.ProjectsListDetail.DetailsClass, global::LightSwitchApplication.WorkItem>.Data _WorkItems;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.ProjectsListDetail, global::LightSwitchApplication.ProjectsListDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.ProjectsListDetail, global::LightSwitchApplication.ProjectsListDetail.DetailsClass, global::LightSwitchApplication.Project> Projects
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.ProjectsListDetail, global::LightSwitchApplication.ProjectsListDetail.DetailsClass, global::LightSwitchApplication.Project>)base.GetItem(global::LightSwitchApplication.ProjectsListDetail.DetailsClass.PropertySetProperties.Projects);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.ProjectsListDetail, global::LightSwitchApplication.ProjectsListDetail.DetailsClass, global::LightSwitchApplication.WorkItem> WorkItems
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.ProjectsListDetail, global::LightSwitchApplication.ProjectsListDetail.DetailsClass, global::LightSwitchApplication.WorkItem>)base.GetItem(global::LightSwitchApplication.ProjectsListDetail.DetailsClass.PropertySetProperties.WorkItems);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.ProjectsListDetail, global::LightSwitchApplication.ProjectsListDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.ProjectsListDetail, global::LightSwitchApplication.ProjectsListDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.ProjectsListDetail, global::LightSwitchApplication.ProjectsListDetail.DetailsClass, global::LightSwitchApplication.Project>.Entry
                    Projects = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.ProjectsListDetail, global::LightSwitchApplication.ProjectsListDetail.DetailsClass, global::LightSwitchApplication.Project>.Entry(
                        "Projects",
                        global::LightSwitchApplication.ProjectsListDetail.DetailsClass.PropertySetProperties._Projects_Stub,
                        global::LightSwitchApplication.ProjectsListDetail.DetailsClass.PropertySetProperties._Projects_Validate,
                        global::LightSwitchApplication.ProjectsListDetail.DetailsClass.PropertySetProperties._Projects_CreateQuery,
                        global::LightSwitchApplication.ProjectsListDetail.DetailsClass.PropertySetProperties._Projects_SelectionChanged,
                        global::LightSwitchApplication.ProjectsListDetail.DetailsClass.PropertySetProperties._Projects_OnCollectionChanged,
                        global::LightSwitchApplication.ProjectsListDetail.DetailsClass.PropertySetProperties._Projects_OnLoaded);
                private static void _Projects_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectsListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.ProjectsListDetail, global::LightSwitchApplication.ProjectsListDetail.DetailsClass, global::LightSwitchApplication.Project>.Data> c, global::LightSwitchApplication.ProjectsListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._Projects, sf);
                }
                private static void _Projects_Validate(global::LightSwitchApplication.ProjectsListDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Projects_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Projects_CreateQuery(global::LightSwitchApplication.ProjectsListDetail.DetailsClass d, object[] args)
                {
                    return d.ProjectsQuery();
                }
                private static void _Projects_SelectionChanged(global::LightSwitchApplication.ProjectsListDetail s)
                {
                    s.Projects_SelectionChanged();
                }
                private static void _Projects_OnCollectionChanged(global::LightSwitchApplication.ProjectsListDetail s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Projects_Changed(e);
                }
                private static void _Projects_OnLoaded(global::LightSwitchApplication.ProjectsListDetail s, bool succeeded)
                {
                    s.Projects_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.ProjectsListDetail, global::LightSwitchApplication.ProjectsListDetail.DetailsClass, global::LightSwitchApplication.WorkItem>.Entry
                    WorkItems = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.ProjectsListDetail, global::LightSwitchApplication.ProjectsListDetail.DetailsClass, global::LightSwitchApplication.WorkItem>.Entry(
                        "WorkItems",
                        global::LightSwitchApplication.ProjectsListDetail.DetailsClass.PropertySetProperties._WorkItems_Stub,
                        global::LightSwitchApplication.ProjectsListDetail.DetailsClass.PropertySetProperties._WorkItems_Validate,
                        global::LightSwitchApplication.ProjectsListDetail.DetailsClass.PropertySetProperties._WorkItems_CreateQuery,
                        global::LightSwitchApplication.ProjectsListDetail.DetailsClass.PropertySetProperties._WorkItems_SelectionChanged,
                        global::LightSwitchApplication.ProjectsListDetail.DetailsClass.PropertySetProperties._WorkItems_OnCollectionChanged,
                        global::LightSwitchApplication.ProjectsListDetail.DetailsClass.PropertySetProperties._WorkItems_OnLoaded);
                private static void _WorkItems_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ProjectsListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.ProjectsListDetail, global::LightSwitchApplication.ProjectsListDetail.DetailsClass, global::LightSwitchApplication.WorkItem>.Data> c, global::LightSwitchApplication.ProjectsListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._WorkItems, sf);
                }
                private static void _WorkItems_Validate(global::LightSwitchApplication.ProjectsListDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.WorkItems_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _WorkItems_CreateQuery(global::LightSwitchApplication.ProjectsListDetail.DetailsClass d, object[] args)
                {
                    return d.WorkItemsQuery();
                }
                private static void _WorkItems_SelectionChanged(global::LightSwitchApplication.ProjectsListDetail s)
                {
                    s.WorkItems_SelectionChanged();
                }
                private static void _WorkItems_OnCollectionChanged(global::LightSwitchApplication.ProjectsListDetail s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.WorkItems_Changed(e);
                }
                private static void _WorkItems_OnLoaded(global::LightSwitchApplication.ProjectsListDetail s, bool succeeded)
                {
                    s.WorkItems_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class WorkItemsListDetail
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.WorkItemsListDetail, global::LightSwitchApplication.WorkItemsListDetail.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private WorkItemsListDetail() : base("LightSwitchApplication:WorkItemsListDetail")
        {
            global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static WorkItemsListDetail CreateInstance()
        {
            return new global::LightSwitchApplication.WorkItemsListDetail(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WorkItemsListDetail_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WorkItemsListDetail_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WorkItemsListDetail_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WorkItemsListDetail_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WorkItemsListDetail_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WorkItemsListDetail_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WorkItemsListDetail_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void WorkItems_SelectionChanged();

        partial void WorkItems_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WorkItems_Loaded(bool succeeded);

        partial void Children_SelectionChanged();

        partial void Children_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Children_Loaded(bool succeeded);

        /// <summary>
        /// Gets the WorkItems visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.WorkItem> WorkItems
        {
            get
            {
                return global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.PropertySetProperties.WorkItems);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void WorkItems_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Gets the Children visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.WorkItem> Children
        {
            get
            {
                return global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.PropertySetProperties.Children);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Children_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.WorkItemsListDetail, global::LightSwitchApplication.WorkItemsListDetail.DetailsClass, global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.PropertySet, global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.CommandSet, global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.PropertySetProperties.WorkItems;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.WorkItemsListDetail, global::LightSwitchApplication.WorkItemsListDetail.DetailsClass>.Entry
                __WorkItemsListDetailEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.WorkItemsListDetail, global::LightSwitchApplication.WorkItemsListDetail.DetailsClass>.Entry(
                    global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.__WorkItemsListDetail_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.__WorkItemsListDetail_InvokeSavingEvent,
                    global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.__WorkItemsListDetail_InvokeSavedEvent,
                    global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.__WorkItemsListDetail_InvokeClosingEvent,
                    global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.__WorkItemsListDetail_InvokeCreated,
                    global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.__WorkItemsListDetail_InvokeActivated,
                    global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.__WorkItemsListDetail_InvokeSaveErrorEvent);
            private static void __WorkItemsListDetail_InvokeInitializeDataWorkspace(global::LightSwitchApplication.WorkItemsListDetail s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.WorkItemsListDetail_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __WorkItemsListDetail_InvokeSavingEvent(global::LightSwitchApplication.WorkItemsListDetail s)
            {
                bool handled = false;
                s.WorkItemsListDetail_Saving(ref handled);
                return handled;
            }
            private static void __WorkItemsListDetail_InvokeSavedEvent(global::LightSwitchApplication.WorkItemsListDetail s)
            {
                s.WorkItemsListDetail_Saved();
            }
            private static bool __WorkItemsListDetail_InvokeClosingEvent(global::LightSwitchApplication.WorkItemsListDetail s)
            {
                bool cancel = false;
                s.WorkItemsListDetail_Closing(ref cancel);
                return cancel;
            }
            private static void __WorkItemsListDetail_InvokeCreated(global::LightSwitchApplication.WorkItemsListDetail s)
            {
                s.WorkItemsListDetail_Created();
            }
            private static void __WorkItemsListDetail_InvokeActivated(global::LightSwitchApplication.WorkItemsListDetail s)
            {
                s.WorkItemsListDetail_Activated();
            }
            private static bool __WorkItemsListDetail_InvokeSaveErrorEvent(global::LightSwitchApplication.WorkItemsListDetail s, global::System.Exception ex)
            {
                bool handled = false;
                s.WorkItemsListDetail_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable WorkItemsQuery()
            {
                return global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                    global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                        global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                            this.Screen.DataWorkspace.ApplicationData.WorkItems,
                            "Project"),
                        "Sprint"),
                    "Parent");
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable ChildrenQuery()
            {
                if (this.Screen.WorkItems.SelectedItem == null)
                {
                    return null;
                }

                global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.WorkItem> loader =
                    (global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.WorkItem>)((global::Microsoft.LightSwitch.Details.ILoadableProperty)this.Screen.WorkItems.SelectedItem.Details.Properties.Children).Loader;
                if (loader == null)
                {
                    return null;
                }

                return global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                    global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                        loader,
                        "Project"),
                    "Sprint");
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkItemsListDetail, global::LightSwitchApplication.WorkItemsListDetail.DetailsClass, global::LightSwitchApplication.WorkItem>.Data _WorkItems;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkItemsListDetail, global::LightSwitchApplication.WorkItemsListDetail.DetailsClass, global::LightSwitchApplication.WorkItem>.Data _Children;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.WorkItemsListDetail, global::LightSwitchApplication.WorkItemsListDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkItemsListDetail, global::LightSwitchApplication.WorkItemsListDetail.DetailsClass, global::LightSwitchApplication.WorkItem> WorkItems
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkItemsListDetail, global::LightSwitchApplication.WorkItemsListDetail.DetailsClass, global::LightSwitchApplication.WorkItem>)base.GetItem(global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.PropertySetProperties.WorkItems);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkItemsListDetail, global::LightSwitchApplication.WorkItemsListDetail.DetailsClass, global::LightSwitchApplication.WorkItem> Children
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkItemsListDetail, global::LightSwitchApplication.WorkItemsListDetail.DetailsClass, global::LightSwitchApplication.WorkItem>)base.GetItem(global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.PropertySetProperties.Children);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.WorkItemsListDetail, global::LightSwitchApplication.WorkItemsListDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.WorkItemsListDetail, global::LightSwitchApplication.WorkItemsListDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkItemsListDetail, global::LightSwitchApplication.WorkItemsListDetail.DetailsClass, global::LightSwitchApplication.WorkItem>.Entry
                    WorkItems = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkItemsListDetail, global::LightSwitchApplication.WorkItemsListDetail.DetailsClass, global::LightSwitchApplication.WorkItem>.Entry(
                        "WorkItems",
                        global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.PropertySetProperties._WorkItems_Stub,
                        global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.PropertySetProperties._WorkItems_Validate,
                        global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.PropertySetProperties._WorkItems_CreateQuery,
                        global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.PropertySetProperties._WorkItems_SelectionChanged,
                        global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.PropertySetProperties._WorkItems_OnCollectionChanged,
                        global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.PropertySetProperties._WorkItems_OnLoaded);
                private static void _WorkItems_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WorkItemsListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkItemsListDetail, global::LightSwitchApplication.WorkItemsListDetail.DetailsClass, global::LightSwitchApplication.WorkItem>.Data> c, global::LightSwitchApplication.WorkItemsListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._WorkItems, sf);
                }
                private static void _WorkItems_Validate(global::LightSwitchApplication.WorkItemsListDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.WorkItems_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _WorkItems_CreateQuery(global::LightSwitchApplication.WorkItemsListDetail.DetailsClass d, object[] args)
                {
                    return d.WorkItemsQuery();
                }
                private static void _WorkItems_SelectionChanged(global::LightSwitchApplication.WorkItemsListDetail s)
                {
                    s.WorkItems_SelectionChanged();
                }
                private static void _WorkItems_OnCollectionChanged(global::LightSwitchApplication.WorkItemsListDetail s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.WorkItems_Changed(e);
                }
                private static void _WorkItems_OnLoaded(global::LightSwitchApplication.WorkItemsListDetail s, bool succeeded)
                {
                    s.WorkItems_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkItemsListDetail, global::LightSwitchApplication.WorkItemsListDetail.DetailsClass, global::LightSwitchApplication.WorkItem>.Entry
                    Children = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkItemsListDetail, global::LightSwitchApplication.WorkItemsListDetail.DetailsClass, global::LightSwitchApplication.WorkItem>.Entry(
                        "Children",
                        global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.PropertySetProperties._Children_Stub,
                        global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.PropertySetProperties._Children_Validate,
                        global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.PropertySetProperties._Children_CreateQuery,
                        global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.PropertySetProperties._Children_SelectionChanged,
                        global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.PropertySetProperties._Children_OnCollectionChanged,
                        global::LightSwitchApplication.WorkItemsListDetail.DetailsClass.PropertySetProperties._Children_OnLoaded);
                private static void _Children_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WorkItemsListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.WorkItemsListDetail, global::LightSwitchApplication.WorkItemsListDetail.DetailsClass, global::LightSwitchApplication.WorkItem>.Data> c, global::LightSwitchApplication.WorkItemsListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._Children, sf);
                }
                private static void _Children_Validate(global::LightSwitchApplication.WorkItemsListDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Children_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Children_CreateQuery(global::LightSwitchApplication.WorkItemsListDetail.DetailsClass d, object[] args)
                {
                    return d.ChildrenQuery();
                }
                private static void _Children_SelectionChanged(global::LightSwitchApplication.WorkItemsListDetail s)
                {
                    s.Children_SelectionChanged();
                }
                private static void _Children_OnCollectionChanged(global::LightSwitchApplication.WorkItemsListDetail s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Children_Changed(e);
                }
                private static void _Children_OnLoaded(global::LightSwitchApplication.WorkItemsListDetail s, bool succeeded)
                {
                    s.Children_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
}
